# Final stage
FROM golang:1.24@sha256:fa073742ff90bad7718e5dae778cd92b81450c396fa379f16acb29955da04959

WORKDIR /go/src/app

# Copy and build the log generator
COPY go.mod go.sum ./
COPY *.go ./
COPY flog/ flog/
COPY log/ log/

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /generator

ENTRYPOINT ["/generator"]
