version: '3.0'

services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    container_name: 'grafana-logsapp'
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall lokiLogsDataplane
      - GF_LOG_FRONTEND_ENABLED=true
      - GF_LOG_FRONTEND_CUSTOM_ENDPOINT=http://localhost:12347/collect
      - GF_TRACING_OPENTELEMETRY_JAEGER_ADDRESS=http://host.docker.internal:14268/api/traces
      - GF_TRACING_OPENTELEMETRY_JAEGER_PROPAGATION=jaeger,w3c
      - GF_PLUGINS_PREINSTALL_DISABLED=true
      - GF_SERVER_ROOT_URL=http://localhost:3001/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GRAFANA_CLOUD_LOGS_KEY=${GRAFANA_CLOUD_LOGS_KEY}
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
    ports: !override
      - 3001:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-logsapp
      - ./provisioning:/etc/grafana/provisioning
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  loki:
    image: grafana/loki:k263-d446d47@sha256:0447cac717544cd00bea3eac8647c0c186b6cb6f024fc517c7d10e347a4e9c9d
    environment:
      LOG_CLUSTER_DEPTH: '8'
      LOG_SIM_TH: '0.3'
    ports:
      - '3100:3100'
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
      - ./config/loki-overrides.yaml:/etc/loki/overrides.yaml
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -runtime-config.file=/etc/loki/overrides.yaml
    restart: on-failure
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  generator:
    build:
      context: ./generator
    command: -url http://loki:3100/loki/api/v1/push -tenant-id=1
    environment:
      - OTLP_ENDPOINT=http://loki:3100/otlp
  alloy:
    image: grafana/alloy:latest@sha256:6ab34b8201f0e8b0c4346be4934c9965723af3f7f21dd9a65fd73f270f69b451
    environment:
      - AGENT_MODE=flow
    command:
      ['run', '--server.http.listen-addr=0.0.0.0:12345', '--stability.level=public-preview', '/etc/alloy/config.alloy']
    volumes:
      - ./config/config.river:/etc/alloy/config.alloy
    ports:
      - '12345:12345'
      - '12347:12347'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  tempo:
    image: grafana/tempo:2.6.0@sha256:f55a8a1937fff0af3a760d376b476c8327fb30e432d5e7630d7938b67691e822
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    ports:
      - '14268:14268' # jaeger ingest
      - '3200:3200' # tempo
      - '4317:4317' # otlp grpc
      - '4318:4318' # otlp http
  prometheus:
    image: prom/prometheus:v2.54.1@sha256:f6639335d34a77d9d9db382b92eeb7fc00934be8eae81dbc03b31cfe90411a94
    ports:
      - '9090:9090'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: >
      --enable-feature=remote-write-receiver
      --enable-feature=exemplar-storage
      --enable-feature=native-histograms
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
