# Mock-only stack for the Playwright e2e suite.
services:
  grafana:
    extends:
      file: docker-compose-defaults.yaml
      service: grafana
    container_name: 'grafana-logsapp'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
    ports: !override
      - 3001:3000/tcp
    extra_hosts:
      # This allows us to connect to other services running on the host machine.
      # 172.17.0.1 is the default Docker bridge network gateway IP address
      # Using "host-gateway" would be more portable across different Docker setups but fails in our CI build
      - 'host.docker.internal:172.17.0.1'
