package log

import (
	"math/rand"
	"sync"
	"sync/atomic"
	"time"

	fake3 "github.com/brianvoe/gofakeit"
	fake7 "github.com/brianvoe/gofakeit/v7"
)

// StaticConfig describes the deterministic time window and step size used by
// the generator when static mode is enabled. In static mode each AppLogger
// emits a bounded number of logs whose timestamps fall inside [Start, End].
type StaticConfig struct {
	Start time.Time
	End   time.Time
	Step  time.Duration
	// Throttle is a small real-time pause between iterations to avoid
	// overwhelming the Loki ingester while pushing the snapshot.
	Throttle time.Duration
}

var (
	staticConfig atomic.Pointer[StaticConfig]
)

// EnableStatic switches the generator to deterministic ("static") mode and
// seeds both gofakeit packages and the math/rand global source. Subsequent
// calls to NewAppLogger pick up the configuration so each goroutine emits
// logs with timestamps generated by a virtual clock.
func EnableStatic(cfg StaticConfig, seed int64) {
	if cfg.Step <= 0 {
		cfg.Step = 5 * time.Second
	}
	if cfg.Throttle <= 0 {
		cfg.Throttle = 100 * time.Microsecond
	}
	staticConfig.Store(&cfg)
	rand.Seed(seed) //nolint:staticcheck // intentional for determinism
	fake3.Seed(seed)
	_ = fake7.Seed(uint64(seed))
}

// CurrentStatic returns the active static configuration, or nil when the
// generator is running in live mode.
func CurrentStatic() *StaticConfig {
	return staticConfig.Load()
}

// StaticEnabled reports whether the generator is running in static mode.
func StaticEnabled() bool {
	return staticConfig.Load() != nil
}

// staticIters returns the number of iterations a single AppLogger should
// emit when static mode is active.
func staticIters() int64 {
	cfg := staticConfig.Load()
	if cfg == nil {
		return 0
	}
	span := cfg.End.Sub(cfg.Start)
	if span <= 0 || cfg.Step <= 0 {
		return 0
	}
	return int64(span / cfg.Step)
}

// generatorWG tracks goroutines spawned via Go(). main can wait on it to
// know when all generator goroutines have exited (used in static mode to
// drive the program to a graceful shutdown).
var generatorWG sync.WaitGroup

// Go spawns a goroutine and registers it with a shared WaitGroup. Used by
// the generator entry points so that main.go can wait for all of them to
// finish before flushing the Loki client and exiting in static mode.
func Go(fn func()) {
	generatorWG.Add(1)
	go func() {
		defer generatorWG.Done()
		fn()
	}()
}

// WaitGenerators blocks until all goroutines started via Go have returned.
func WaitGenerators() {
	generatorWG.Wait()
}
