apiVersion: 1

datasources:
  - name: gdev-testdata
    isDefault: true
    type: testdata
  - name: gdev-loki
    type: loki
    uid: gdev-loki
    access: proxy
    url: http://host.docker.internal:3100
    jsonData:
      httpHeaderName1: 'X-Scope-OrgID'
      derivedFields:
        - datasourceUid: gdev-jaeger
          matcherRegex: traceID
          matcherType: label
          name: traceID-jaeger
          url: '$${__value.raw}'
          urlDisplayLabel: jaeger
        - datasourceUid: gdev-zipkin
          matcherRegex: traceID
          matcherType: label
          name: traceID-zipkin
          url: '$${__value.raw}'
        - datasourceUid: gdev-tempo
          matcherRegex: traceID
          matcherType: label
          name: traceID-tempo
          url: '$${__value.raw}'
          urlDisplayLabel: tempo
    secureJsonData:
      httpHeaderValue1: '1'
  - name: gdev-tempo
    type: tempo
    uid: gdev-tempo
    access: proxy
    url: http://host.docker.internal:3200
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: gdev-loki
        spanStartTimeShift: '5m'
        spanEndTimeShift: '-5m'
        customQuery: true
        query: '{filename="/var/log/grafana/grafana.log"} |="$${__span.traceId}"'
  - name: gdev-prometheus
    uid: gdev-prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    basicAuth: true #username: admin, password: admin
    basicAuthUser: admin
    jsonData:
      manageAlerts: true
      alertmanagerUid: gdev-alertmanager
      prometheusType: Prometheus #Cortex | Mimir | Prometheus | Thanos
      prometheusVersion: 2.40.0
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: gdev-tempo
    secureJsonData:
      basicAuthPassword: admin #https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables
  - name: grafanacloud-dev-logs
    type: loki
    typeName: Loki
    typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
    uid: grafanacloud-dev-logs
    url: https://logs-dev-005.grafana-dev.net
    basicAuth: true
    isDefault: false
    basicAuthUser: 29
    secureJsonData:
      basicAuthPassword: ${GRAFANA_CLOUD_LOGS_KEY}
