name: Plugins - CI / CD

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  debug:
    name: Debug Information
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Base Ref: ${{ github.event.pull_request.base.ref }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Run Playwright: ${{ (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') && 'true' || 'false' }}"

  cd:
    name: CI / CD
    uses: grafana/plugin-ci-workflows/.github/workflows/cd.yml@main # zizmor: ignore[unpinned-uses]
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      # Checkout/build PR or main branch, depending on event
      branch: ${{ github.event_name == 'push' && github.ref_name || github.ref }}

      # When pushing to "main", publish and deploy to "dev" and "ops" (CD). For PRs, skip publishing and deploying (run CI only)
      environment: ${{ (github.event_name == 'push' && github.ref_name == 'main') && 'dev' || 'ops' || 'none' }}

      # Deploy provisioned plugin to Grafana Cloud
      grafana-cloud-deployment-type: provisioned
      argo-workflow-slack-channel: '#drilldown-cd-alerts-dev-ops'

      # Add the git head ref sha to the plugin version as suffix (`+abcdef`). This is required for CD builds.
      plugin-version-suffix: ${{ github.event_name == 'push' && github.sha || github.event.pull_request.head.sha }}

      # Run playwright only on PR and not on merge to main
      run-playwright: ${{ (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') && 'true' || 'false' }}

      # Same settings as publish
      run-playwright-with-skip-grafana-dev-image: true
      run-playwright-with-grafana-dependency: '>=12.0.0'
      upload-playwright-artifacts: true
      playwright-docker-compose-file: docker-compose.dev.yaml
      playwright-grafana-url: http://localhost:3001/grafana
