name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@main
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      run-playwright-with-grafana-dependency: 'latest'
      upload-playwright-artifacts: true
      playwright-report-path: tests/test-reports/
      playwright-docker-compose-file: docker-compose.dev.yaml
      playwright-grafana-url: http://localhost:3001
