name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@main
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      run-playwright: false
      run-playwright-docker: true
      run-playwright-with-grafana-dependency: '11.6.0'
      upload-playwright-artifacts: true
      playwright-grafana-url: http://localhost:3001
