name: Release main to latest

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore: # Don't run the workflow if only .github/** or docs/** files have been changed
      - '.github/**'
      - 'docs/**'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-latest-version:
    runs-on: ubuntu-latest

    outputs:
      upload-folder: ${{ steps.metadata.outputs.upload-folder }}

    steps:
      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@28361cdb22223e5f1e34358c86c20908e7248760
        with:
          common_secrets: |
            GRAFANA_ACCESS_POLICY_TOKEN=plugins/sign-plugin-access-policy-token:token
            GCP_UPLOAD_ARTIFACTS_KEY=grafana/integration-artifacts-uploader-service-account:'credentials.json'

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: bump package version
        run: npm version --no-git-tag-version patch && npm version --no-git-tag-version `npm version --json | jq -r '."grafana-lokiexplore-app"'`-`git rev-parse --short HEAD`
      - uses: grafana/plugin-actions/package-plugin@main
        id: 'package-plugin'
        with:
          policy_token: ${{ env.GRAFANA_ACCESS_POLICY_TOKEN }}      

      - id: 'auth'
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          credentials_json: ${{ env.GCP_UPLOAD_ARTIFACTS_KEY }}

      - name: 'rename versioned archive to main-archive'
        env:
          ARCHIVE_PATH: ${{ steps.package-plugin.outputs.archive }}
          PLUGIN_ID: ${{ steps.package-plugin.outputs.plugin-id }}
        run: |
          mv "$ARCHIVE_PATH" "${PLUGIN_ID}-main.zip"

      - id: 'upload-to-gcs'
        name: 'Upload assets to latest'
        uses: google-github-actions/upload-cloud-storage@e95a15f226403ed658d3e65f40205649f342ba2c # v1.0.3
        with:
          path: ./
          destination: 'integration-artifacts/grafana-lokiexplore-app/'
          glob: '*.zip'
          parent: false

      - id: 'upload-to-gcs-main'
        name: 'Upload assets to latest'
        uses: google-github-actions/upload-cloud-storage@e95a15f226403ed658d3e65f40205649f342ba2c # v1.0.3
        with:
          path: ./
          destination: 'integration-artifacts/grafana-lokiexplore-app/release/main/any/'
          glob: '*.zip'
          parent: false
