name: Version PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      generate-changelog:
        description: 'Generate changelog'
        required: false
        type: boolean
        default: true
      create-pr:
        description: 'Create a pull request'
        required: false
        type: boolean
        default: true
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Version bump
        uses: grafana/plugin-ci-workflows/actions/plugins/version-bump-changelog@l2d2/version-bump-changelog-open-pr
        with:
          generate-changelog: ${{ inputs.generate-changelog }}
          version: ${{ inputs.version }}
          create-pr: ${{ inputs.create-pr }}
